-- CreateEnum
CREATE TYPE "proficiency" AS ENUM ('NOT_PROEFFICIENT', 'PROFFICIENT', 'SPECIALIST');

-- AlterTable
ALTER TABLE "Character" ADD COLUMN     "acrobatics" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "animalHandling" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "arcana" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "athletics" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "charisma" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "charismaSavingThrow" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "constitution" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "constitutionSavingThrow" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "deception" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "dexterity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dexteritySavingThrow" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "history" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "insight" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "intelligence" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "intelligenceSavingThrow" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "intimidation" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "investigation" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "medicine" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "nature" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "perception" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "performance" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "persuasion" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "religion" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "sleightOfHand" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "stealth" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "strength" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "strengthSavingThrow" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "survival" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "tecnology" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT',
ADD COLUMN     "wisdom" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "wisdomSavingThrow" "proficiency" NOT NULL DEFAULT E'NOT_PROEFFICIENT';
